
--- RELATORIOS PARA A GESTÃO DA CLINICA ---


--- (1) CONTROLE BASICO DE ESTOQUE DE FARMACOS (Baixo Estoque / Próximo da Validade)

CREATE OR REPLACE FUNCTION RELATORIO_ESTOQUE_FARMACOS()
RETURNS TABLE (
	NOME_FARMACO VARCHAR,
	QUANTIDADE INT,
	VALIDADE DATE,
	DIAS_RESTANTES_VENC INT,
	STATUS_ESTOQUE TEXT
) AS $$
BEGIN
	RETURN QUERY
	SELECT
		F.NOME AS NOME_FARMACO,
		F.QUANT AS QUANTIDADE,
		F.VALIDADE AS VALIDADE,
		GREATEST((F.VALIDADE - CURRENT_DATE),0) AS DIAS_RESTANTES_VENC,
		CASE
			WHEN F.VALIDADE <= CURRENT_DATE THEN
				'❌ Vencido'
			WHEN (F.VALIDADE - CURRENT_DATE) <= 90 AND F.QUANT <= 10 THEN
				'⚠️ Critico: Farmaco proximo do vencimento e com baixo estoque...'
			WHEN (F.VALIDADE - CURRENT_DATE) <= 90 THEN
				'⚠️ Farmaco proximo do vencimento'
			WHEN F.QUANT <= 10 THEN
				'⚠️ Farmaco com baixo estoque...'
			ELSE
				'✅ Em estoque'
				
		 END AS STATUS_ESTOQUE
		
	FROM FARMACO F
	ORDER BY STATUS_ESTOQUE DESC;
	
END;
$$ LANGUAGE PLPGSQL;

--- (2) RELATORIO DE RECEITA DETALHADA POR SERVICO/ESPECIALIDADE (Identificar os serviços mais lucrativos)


--- (3) RELATORIO DE DIAGNOSTICOS MAIS COMUNS (Doenças são mais frequentes)