
----- CRIAÇÃO DAS TABELAS -----

CREATE TABLE TUTOR (
COD_TUTOR SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL,
DT_NASC DATE NOT NULL,
FONE VARCHAR(15) NOT NULL
)


CREATE TABLE PLANO_PET (
COD_PLANO_PET SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
VALOR FLOAT NOT NULL,
DESCONTO_CONSULTA FLOAT NOT NULL,
DESCONTO_VACINACAO FLOAT NOT NULL
)

CREATE TABLE PET (
COD_PET SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DT_NASC DATE NOT NULL,
ESPECIE VARCHAR(50) NOT NULL,
PORTE VARCHAR(50) NOT NULL,

COD_TUTOR INT REFERENCES TUTOR(COD_TUTOR)
)


CREATE TABLE VINCULO (
COD_VINCULO SERIAL NOT NULL PRIMARY KEY,
DT_CONTRATACAO DATE NOT NULL,
STATUS BOOLEAN NOT NULL,

COD_PET INT REFERENCES PET(COD_PET),
COD_PLANO_PET INT REFERENCES PLANO_PET(COD_PLANO_PET)
)


CREATE TABLE ESPECIALIDADE (
COD_ESPE SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DESCR TEXT NOT NULL
)


CREATE TABLE VETERINARIO (
COD_VET SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CRMV INT NOT NULL,

COD_ESPE INT REFERENCES ESPECIALIDADE(COD_ESPE)
)


CREATE TABLE ATENDENTE (
COD_ATEND INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DT_NASC DATE NOT NULL,
SALARIO FLOAT NOT NULL
)

CREATE TABLE PAGAMENTO (
COD_PAG INT NOT NULL PRIMARY KEY,
FORMA_PAG VARCHAR(10) NOT NULL
)

CREATE TABLE PARCELA (
COD_PARC INT NOT NULL PRIMARY KEY,
VENC DATE NOT NULL,
VALOR FLOAT NOT NULL,
STATUS BOOLEAN NOT NULL,

COD_PAG INT REFERENCES PAGAMENTO(COD_PAG)
)

CREATE TABLE CONSULTA (
COD_CONSULTA SERIAL NOT NULL PRIMARY KEY,
DATA DATE NOT NULL,
HORA TIMESTAMP NOT NULL,
DIAGNOSTICO TEXT NOT NULL,

COD_VET INT REFERENCES VETERINARIO(COD_VET),
COD_VINCULO INT REFERENCES VINCULO(COD_VINCULO),
COD_ATEND INT REFERENCES ATENDENTE(COD_ATEND),
COD_PAG INT REFERENCES PAGAMENTO(COD_PAG)
)


CREATE TABLE VACINACAO (
COD_VACINACAO INT NOT NULL PRIMARY KEY,
DATA DATE NOT NULL,
HORA TIMESTAMP NOT NULL,

COD_VET INT REFERENCES VETERINARIO(COD_VET),
COD_VINCULO INT REFERENCES VINCULO(COD_VINCULO),
COD_ATEND INT REFERENCES ATENDENTE(COD_ATEND),
COD_PAG INT REFERENCES PAGAMENTO(COD_PAG)
)


CREATE TABLE MEDICACAO (
COD_MEDICACAO INT NOT NULL PRIMARY KEY,
DATA DATE NOT NULL,
HORA TIMESTAMP NOT NULL,

COD_CONSULTA INT REFERENCES CONSULTA(COD_CONSULTA)
)


CREATE TABLE TIPO (
COD_TIPO INT NOT NULL PRIMARY KEY,
NOME VARCHAR(30)
)


CREATE TABLE FARMACO (
COD_FARM INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DOSE FLOAT NOT NULL,
VALIDADE DATE NOT NULL,
LOTE VARCHAR(30) NOT NULL,
DT_ENTRADA DATE NOT NULL,
VALOR FLOAT NOT NULL,
QUANT INT NOT NULL,

COD_TIPO INT REFERENCES TIPO(COD_TIPO)
)


CREATE TABLE ITEM_VACINACAO (
COD_ITEM_VACINACAO INT NOT NULL PRIMARY KEY,

COD_VACINACAO INT REFERENCES VACINACAO(COD_VACINACAO),
COD_FARM INT REFERENCES FARMACO(COD_FARM)
)

CREATE TABLE ITEM_MEDICACAO (
COD_ITEM_MEDICACAO INT NOT NULL PRIMARY KEY,

COD_MEDICACAO INT REFERENCES MEDICACAO(COD_MEDICACAO),
COD_FARM INT REFERENCES FARMACO(COD_FARM)
)




