
----- CRIAÇÃO DAS TABELAS -----

CREATE TABLE TUTOR (
COD_TUTOR SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL,
DT_NASC DATE NOT NULL,
FONE VARCHAR(15) NOT NULL
);


CREATE TABLE PLANO_PET (
COD_PLANO_PET SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
VALOR FLOAT NOT NULL,
DESCONTO_CONSULTA FLOAT NOT NULL,
DESCONTO_VACINACAO FLOAT NOT NULL
);

CREATE TABLE PET (
COD_PET SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DT_NASC DATE NOT NULL,
ESPECIE VARCHAR(50) NOT NULL,
PORTE VARCHAR(50) NOT NULL,
SEXO VARCHAR(1) NOT NULL,

COD_TUTOR INT REFERENCES TUTOR(COD_TUTOR)
);


CREATE TABLE VINCULO (
COD_VINCULO SERIAL NOT NULL PRIMARY KEY,
DT_CONTRATACAO DATE NOT NULL,
STATUS BOOLEAN NOT NULL,

COD_PET INT REFERENCES PET(COD_PET),
COD_PLANO_PET INT REFERENCES PLANO_PET(COD_PLANO_PET)
);


CREATE TABLE ESPECIALIDADE (
COD_ESP SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DESCR TEXT NOT NULL,
VALOR FLOAT NOT NULL
);


CREATE TABLE VETERINARIO (
COD_VET SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CRMV VARCHAR(15) NOT NULL,

COD_ESP INT REFERENCES ESPECIALIDADE(COD_ESP)
);


CREATE TABLE ATENDENTE (
COD_ATEND SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DT_NASC DATE NOT NULL,
SALARIO FLOAT NOT NULL
);


CREATE TABLE PAGAMENTO (
COD_PAG SERIAL NOT NULL PRIMARY KEY,
FORMA_PAG VARCHAR(20) NOT NULL,
VALOR_TOTAL FLOAT NOT NULL,
QUANT_PARCELAS INT NOT NULL,
DATA DATE NOT NULL
);

CREATE TABLE PARCELA (
COD_PARC SERIAL NOT NULL PRIMARY KEY,
VENC DATE NOT NULL,
VALOR FLOAT NOT NULL,
STATUS BOOLEAN NOT NULL,

COD_PAG INT REFERENCES PAGAMENTO(COD_PAG)
);


CREATE TABLE TIPO (
COD_TIPO SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(30)
);


CREATE TABLE FARMACO (
COD_FARM SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DOSE VARCHAR(10) NOT NULL,
VALIDADE DATE NOT NULL,
LOTE VARCHAR(30) NOT NULL,
DT_ENTRADA DATE NOT NULL,
VALOR FLOAT NOT NULL,
QUANT INT NOT NULL,

COD_TIPO INT REFERENCES TIPO(COD_TIPO)
);


CREATE TABLE MEDICACAO (
COD_MEDICACAO SERIAL NOT NULL PRIMARY KEY,
DATA DATE NOT NULL,
HORA TIME NOT NULL,

COD_FARM INT REFERENCES FARMACO(COD_FARM)
);


CREATE TABLE CONSULTA (
COD_CONSULTA SERIAL NOT NULL PRIMARY KEY,
DATA DATE NOT NULL,
HORA TIME NOT NULL,
DIAGNOSTICO TEXT NOT NULL,

COD_VET INT REFERENCES VETERINARIO(COD_VET),
COD_VINCULO INT REFERENCES VINCULO(COD_VINCULO),
COD_ATEND INT REFERENCES ATENDENTE(COD_ATEND),
COD_PAG INT REFERENCES PAGAMENTO(COD_PAG),
COD_MEDICACAO INT REFERENCES MEDICACAO(COD_MEDICACAO)
);


CREATE TABLE VACINACAO (
COD_VACINACAO SERIAL NOT NULL PRIMARY KEY,
DATA DATE NOT NULL,
HORA TIME NOT NULL,

COD_VET INT REFERENCES VETERINARIO(COD_VET),
COD_VINCULO INT REFERENCES VINCULO(COD_VINCULO),
COD_ATEND INT REFERENCES ATENDENTE(COD_ATEND),
COD_PAG INT REFERENCES PAGAMENTO(COD_PAG),
COD_FARM INT REFERENCES FARMACO(COD_FARM)
);
