
-- ╔═══════════════════════════════════════╗
-- ║     CONTROLE DE ACESSO NA CLINICA     ║
-- ╚═══════════════════════════════════════╝

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;

--- CRIAÇÃO DOS ROLES (GRUPOS DE USUARIOS)

CREATE ROLE GRUPO_ATENDENTE NOLOGIN;
CREATE ROLE GRUPO_TUTOR NOLOGIN;
CREATE ROLE GRUPO_VETERINARIO NOLOGIN;


-- ==================================
-- =  PERMISSOES PARA ATENDENTE 🧑‍💻 =
-- ==================================

GRANT EXECUTE ON FUNCTION
    INSERIR_DADOS(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT),
    ATUALIZAR_DADOS(TEXT, TEXT, TEXT),
    DELETAR_DADOS(TEXT, TEXT),
    CADASTRAR_TUTOR(VARCHAR, VARCHAR, DATE, VARCHAR),
	EXCLUIR_TUTOR(VARCHAR),
    CADASTRAR_PET(VARCHAR, DATE, VARCHAR, VARCHAR, VARCHAR, VARCHAR),
	EXCLUIR_PET(VARCHAR, VARCHAR),
    CADASTRAR_PLANO_PET(VARCHAR, FLOAT, FLOAT, FLOAT),
	EXCLUIR_PLANO_PET(VARCHAR),
    CADASTRAR_ATENDENTE(VARCHAR, DATE, FLOAT),
	EXCLUIR_ATENDENTE(VARCHAR),
    CADASTRAR_VETERINARIO(VARCHAR, VARCHAR, VARCHAR),
	EXCLUIR_VETERINARIO(VARCHAR),
    CADASTRAR_ESPECIALIDADE(VARCHAR, TEXT, FLOAT),
	EXCLUIR_ESPECIALIDADE(VARCHAR),
    CADASTRAR_FARMACO(VARCHAR, VARCHAR, DATE, VARCHAR, FLOAT, INT, VARCHAR),
	EXCLUIR_FARMACO(VARCHAR),
    CONTRATAR_PLANO_PET(VARCHAR, VARCHAR, VARCHAR),
    REALIZAR_CONSULTA(VARCHAR, VARCHAR, VARCHAR, VARCHAR, INT, VARCHAR, TEXT),
    REALIZAR_CONSULTA(VARCHAR, VARCHAR, VARCHAR, VARCHAR, INT, VARCHAR, TEXT, VARCHAR),
    REALIZAR_VACINACAO(VARCHAR, VARCHAR, VARCHAR, VARCHAR, INT, VARCHAR, VARCHAR),
    REABASTECER_ESTOQUE(VARCHAR, INT)
TO GRUPO_ATENDENTE;


GRANT EXECUTE ON FUNCTION
    RELATORIO_ESTOQUE_FARMACOS(),
    RELATORIO_FATURAMENTO_DA_CLINICA(TEXT, TEXT),
    RELATORIO_AGENDA_DO_DIA(TEXT, TEXT)
TO GRUPO_ATENDENTE;


-- ====================================
-- =  PERMISSOES PARA VETERINARIO 🧑‍⚕️ =
-- ====================================


GRANT EXECUTE ON FUNCTION
	RELATORIO_HISTORICO_PACIENTE(VARCHAR, VARCHAR),
    RELATORIO_CONS_VAC_REALIZADAS(VARCHAR, TEXT, TEXT)
TO GRUPO_VETERINARIO;


-- ==============================
-- =  PERMISSOES PARA TUTOR 🐶 =
-- ==============================


GRANT EXECUTE ON FUNCTION
	RELATORIO_HISTORICO_DO_SEU_PET(VARCHAR, VARCHAR, TEXT),
    RELATORIO_SEUS_GASTOS(VARCHAR, TEXT, TEXT),
    RELATORIO_VISUALIZAR_PERFIL_DO_PET(VARCHAR, VARCHAR)
TO GRUPO_TUTOR;


-- =========================================
-- =  CRIACAO DE USUARIOS E ATRIBUIR ROLES =
-- =========================================


-- 🧑‍💻
CREATE USER user_leticia WITH PASSWORD 'senha_atendente_123';
GRANT GRUPO_ATENDENTE TO user_leticia;

-- 🧑‍⚕️
CREATE USER user_ricardo WITH PASSWORD 'senha_veterinario_456';
GRANT GRUPO_VETERINARIO TO user_ricardo;

-- 🐶
CREATE USER user_anaclara WITH PASSWORD 'senha_tutor_789';
GRANT GRUPO_TUTOR TO user_anaclara;